# Form implementation generated from reading ui file 'UI/GenerateStraightTrajectory.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(864, 508)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(parent=Form)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_12.setContentsMargins(-1, 1, 1, 1)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.dSB_distance = QtWidgets.QDoubleSpinBox(parent=self.frame_10)
        self.dSB_distance.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dSB_distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dSB_distance.setDecimals(0)
        self.dSB_distance.setMaximum(999999.0)
        self.dSB_distance.setProperty("value", 8000.0)
        self.dSB_distance.setObjectName("dSB_distance")
        self.gridLayout_12.addWidget(self.dSB_distance, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_10, 0, 0, 1, 1)
        self.f_3DView = Widget3D(parent=Form)
        self.f_3DView.setObjectName("f_3DView")
        self.gridLayout.addWidget(self.f_3DView, 0, 1, 4, 1)
        self.frame_4 = QtWidgets.QFrame(parent=Form)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(-1, 1, 1, 1)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.dSB_speed = QtWidgets.QDoubleSpinBox(parent=self.frame_4)
        self.dSB_speed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dSB_speed.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dSB_speed.setDecimals(0)
        self.dSB_speed.setMaximum(1000.0)
        self.dSB_speed.setProperty("value", 800.0)
        self.dSB_speed.setObjectName("dSB_speed")
        self.gridLayout_5.addWidget(self.dSB_speed, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.pB_generate = QtWidgets.QPushButton(parent=Form)
        self.pB_generate.setObjectName("pB_generate")
        self.gridLayout.addWidget(self.pB_generate, 2, 0, 1, 1)
        self.pB_startTranslation = QtWidgets.QPushButton(parent=Form)
        self.pB_startTranslation.setObjectName("pB_startTranslation")
        self.gridLayout.addWidget(self.pB_startTranslation, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_14.setText(_translate("Form", "Дистанция"))
        self.label_8.setText(_translate("Form", "Скорость"))
        self.pB_generate.setText(_translate("Form", "Сгенерировать"))
        self.pB_startTranslation.setText(_translate("Form", "Начать трансляцию"))
from UI.CustomWidgets.Widget3D import Widget3D


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
