# Form implementation generated from reading ui file 'UI/MainForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.p_generateTrajectory = GenerateTrajectoryOptions()
        self.p_generateTrajectory.setObjectName("p_generateTrajectory")
        self.stackedWidget.addWidget(self.p_generateTrajectory)
        self.p_newGenerateTrajectory = NewGenerateTrajectoryOptions()
        self.p_newGenerateTrajectory.setObjectName("p_newGenerateTrajectory")
        self.stackedWidget.addWidget(self.p_newGenerateTrajectory)
        self.p_translateSignal = TranslateTrajectoryOptions()
        self.p_translateSignal.setObjectName("p_translateSignal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.p_translateSignal)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget.addWidget(self.p_translateSignal)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.a_showGenerateTrajectoryPage = QtGui.QAction(parent=MainWindow)
        self.a_showGenerateTrajectoryPage.setObjectName("a_showGenerateTrajectoryPage")
        self.a_loadTrajectory = QtGui.QAction(parent=MainWindow)
        self.a_loadTrajectory.setObjectName("a_loadTrajectory")
        self.a_showTranslation = QtGui.QAction(parent=MainWindow)
        self.a_showTranslation.setObjectName("a_showTranslation")
        self.a_saveTrajectory = QtGui.QAction(parent=MainWindow)
        self.a_saveTrajectory.setObjectName("a_saveTrajectory")
        self.menu.addAction(self.a_saveTrajectory)
        self.menu.addAction(self.a_loadTrajectory)
        self.menu.addAction(self.a_showGenerateTrajectoryPage)
        self.menu.addAction(self.a_showTranslation)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.a_showGenerateTrajectoryPage.setText(_translate("MainWindow", "Сгенерировать траекторию"))
        self.a_loadTrajectory.setText(_translate("MainWindow", "Загрузить траекторию"))
        self.a_showTranslation.setText(_translate("MainWindow", "Трансляция"))
        self.a_saveTrajectory.setText(_translate("MainWindow", "Сохранить траекторию"))
from UI_Options.GenerateTrajectory_Options import GenerateTrajectoryOptions
from UI_Options.NewGenerateTrajectory_Options import NewGenerateTrajectoryOptions
from UI_Options.TranslateTrajectory_Options import TranslateTrajectoryOptions


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
