# Form implementation generated from reading ui file 'UI/TranslateTrajectory.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(612, 365)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = Widget3D(parent=Form)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dSB_delay = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.dSB_delay.setWrapping(False)
        self.dSB_delay.setReadOnly(False)
        self.dSB_delay.setAccelerated(False)
        self.dSB_delay.setProperty("showGroupSeparator", False)
        self.dSB_delay.setDecimals(1)
        self.dSB_delay.setMaximum(200.0)
        self.dSB_delay.setSingleStep(0.1)
        self.dSB_delay.setObjectName("dSB_delay")
        self.gridLayout_2.addWidget(self.dSB_delay, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.l_translation_time = QtWidgets.QLabel(parent=self.frame)
        self.l_translation_time.setText("")
        self.l_translation_time.setObjectName("l_translation_time")
        self.gridLayout_2.addWidget(self.l_translation_time, 1, 1, 1, 1)
        self.pB_start_translation = QtWidgets.QPushButton(parent=self.frame)
        self.pB_start_translation.setObjectName("pB_start_translation")
        self.gridLayout_2.addWidget(self.pB_start_translation, 4, 0, 1, 1)
        self.pB_stop_translation = QtWidgets.QPushButton(parent=self.frame)
        self.pB_stop_translation.setEnabled(False)
        self.pB_stop_translation.setObjectName("pB_stop_translation")
        self.gridLayout_2.addWidget(self.pB_stop_translation, 4, 1, 1, 1)
        self.l_sygnal = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_sygnal.sizePolicy().hasHeightForWidth())
        self.l_sygnal.setSizePolicy(sizePolicy)
        self.l_sygnal.setMinimumSize(QtCore.QSize(50, 50))
        self.l_sygnal.setMaximumSize(QtCore.QSize(50, 50))
        self.l_sygnal.setText("")
        self.l_sygnal.setObjectName("l_sygnal")
        self.gridLayout_2.addWidget(self.l_sygnal, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Задержка перед стартом:"))
        self.label.setText(_translate("Form", "Время трансляции:"))
        self.pB_start_translation.setText(_translate("Form", "Начать трансляцию"))
        self.pB_stop_translation.setText(_translate("Form", "Завершить трансляцию"))
from UI.CustomWidgets.Widget3D import Widget3D


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
